### ISSUE TITLE
kiosk restarts and blocks a lot since v0.14.3

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1350]
Kiosk is just all of a sudden blocking entirely and then later the PID / Thread message pops up which indicates that a process has been restarted. IT gets particulary bad when clicking on the logo.

**Comment by luizaogs** [comment]
I tried a few things (workstation export and import, synchronization, file repository upload) and everything was fine. 

For the sake of completeness, I will report that things got unresponsive when I was downloading my workstation, even if the download worked properly in the end. In fact when I clicked out of the "the workstation is downloading and could be finished" window my workstation did not show up as "in the field" immediately as it usually does (I think?). I then tried to refresh to see if that would help, while the file was downloading in the background, and everything froze and I had to close the tab and it took me another couple of tries to be able to get in normally. But I do not know if this is due to a bad internet connection, though I will say that other websites were working at the same time.

Also, though synchronization seems to have run normally, I was unable to see the complete logs even when clicking on the "show more details" option. Not sure if that is related to this, either.

<img width="1512" alt="Screen Shot 2022-02-11 at 10 18 55 PM" src="https://user-images.githubusercontent.com/67970402/153696257-7747ec42-edb8-4f4f-8115-fa26d96f8df5.png">

And that "system information" banner has been here since I exported my workstation, I believe. Not sure if it should be there.

**Comment by urapadmin** [comment]
> For the sake of completeness, I will report that things got unresponsive when I was downloading my workstation, even if the download worked properly in the end. In fact when I clicked out of the "the workstation is downloading and could be finished" window my workstation did not show up as "in the field" immediately as it usually does (I think?). I then tried to refresh to see if that would help, while the file was downloading in the background, and everything froze and I had to close the tab and it took me another couple of tries to be able to get in normally. But I do not know if this is due to a bad internet connection, though I will say that other websites were working at the same time.

Sounds as if the server restarted for some reason. During that process it is not responding for quite a while.
> 
> Also, though synchronization seems to have run normally, I was unable to see the complete logs even when clicking on the "show more details" option. Not sure if that is related to this, either.
That sounds more like a new bug. I think I have seen that myself at some point. I'll make that a new ticket.

> And that "system information" banner has been there since I exported my workstation, I believe. Not sure if it should be there.
For testing reasons, currently a new system information banner is created whenever a new server process is started (which can happen all the time). That is not the same as if the sever is restarting (in which case ALL server processes are killed and get restarted as demand requires).

**Comment by luizaogs** [comment]
Ah ok, so it sounds like this is all fine? I tried exporting again and it worked as it should. But I don't know if you need Laurel and/or Meghan to test it too so won't close it.

**Comment by urapadmin** [comment]
> Ah ok, so it sounds like this is all fine (other than the new ticket)? I tried exporting again and it worked as it should. But I don't know if you need Laurel and/or Meghan to test it too so won't close it.

It seems to be "normal" at least - I will investigate the untimely server restart and the missing synchronization log.
However, let's leave this open for a while and gather more experiences. Whether or not Beset lacks stability is not as clear a case to test. So please keep reporting if you encounter unusual delays.

**Comment by urapadmin** [comment]
I think this can be closed.
