### ISSUE TITLE
file export: changing from Excel to CSV still exports Excel files

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#1365]
@luizaogs reported:
Hmm ok lastly I was going to try exporting it all as CSV files, but I got the same Excel sheets again after changing the settings. Not sure if something went wrong with the fork?

<img width="575" alt="Screen Shot 2022-02-12 at 11 41 04 PM" src="https://user-images.githubusercontent.com/67970402/153740500-a29dcd1f-ce05-4c5d-8e3f-648f746c4474.png">

<img width="895" alt="Screen Shot 2022-02-12 at 11 43 19 PM" src="https://user-images.githubusercontent.com/67970402/153740535-fc4f1332-238a-4f3e-9fd1-78d5e294d562.png">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/kiosk/issues/438#issuecomment-1037804338_

**Comment by luizaogs** [comment]
Ok, this is really weird. Last night I exported as CSVs twice, once I realized it hadn't worked the first time, and I went back to those zips now and I only have Excel spreadsheets. But I just re-downloaded the zip in the file manager now and got CSVs. 

I'm going to try exporting one more time.

**Comment by luizaogs** [comment]
Yeah, well, it worked again. Maybe I've lost my mind.

**Comment by urapadmin** [comment]
Please don't. It's needed!

And keep an eye on it. Perhaps it happens again.

**Comment by luizaogs** [comment]
Um...this just happened again.

**Comment by luizaogs** [comment]
The second time I downloaded it it worked properly. Oh man.

**Comment by luizaogs** [comment]
Ok, so that we can perhaps agree that I have not indeed gone crazy: 

Time of export was 21:13. I have two zip files from 20:14 and 20:15 (PVD 21:14 and 21:15).

The first, kiosk-export (11) has Excel files. The second, kiosk-export (12) has CSV files. They are from the same file in the file manager.

<img width="715" alt="Screen Shot 2022-02-13 at 8 18 40 PM" src="https://user-images.githubusercontent.com/67970402/153788924-6a89da8f-bad3-4b7a-86de-daeabbb3eb3e.png">

<img width="914" alt="Screen Shot 2022-02-13 at 8 19 56 PM" src="https://user-images.githubusercontent.com/67970402/153789014-c96e9c94-a5ee-4ef5-9a99-71556601bfc8.png">

<img width="917" alt="Screen Shot 2022-02-13 at 8 20 13 PM" src="https://user-images.githubusercontent.com/67970402/153789066-5c3ddacd-f62b-4784-abd0-7b1736dbd53a.png">

<img width="914" alt="Screen Shot 2022-02-13 at 8 20 19 PM" src="https://user-images.githubusercontent.com/67970402/153789076-f631272e-ad0b-4a03-80a7-8e21d4591841.png">

**Comment by lbestock** [comment]
You guys are both nuts. Luiza, you won't believe it, but Lutz is working like a maniac while the kids destroy the kitchen right next to him, and sometimes he responds to them by putting Madonna on?? We're back to Nina Simone which seems saner, but "sane" is not a word that has tons of meaning right now. I'm still in talatat land, so differently insane.

**Comment by luizaogs** [comment]
Maybe I should play some Madonna. What is sanity?

**Comment by urapadmin** [comment]
there is no :lunatic smiley

**Comment by urapadmin** [comment]
could it be a cache issue? Did it actually download both times?

**Comment by urapadmin** [comment]
dumb question. Of course it must have.

**Comment by luizaogs** [comment]
Yes :)

**Comment by urapadmin** [comment]
wait, what is even wrong about it?

**Comment by urapadmin** [comment]
so you downloaded the same file (without exporting beween) from the file manager but got two different results?!?

**Comment by luizaogs** [comment]
Yes! I swear. This is what happened last night, too.

**Comment by urapadmin** [comment]
that is hard to believe 😦 (How is that a frowning smiley?)

**Comment by luizaogs** [comment]
The timestamps are all weird and do not match. I don't know if that could have anything to do with it.

**Comment by urapadmin** [comment]
#1370 might be the same issue. It looks like a caching issue or so. I just don't understand why you would get a different filename then.

**Comment by urapadmin** [comment]
closed in favour of #1372
