### ISSUE TITLE
upload workstation takes way too long

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#44]
the Flask upload is Schrott. I have to find a better way. Currently we cannot upload workstation files to an online kiosk.

**Comment by urapadmin** [comment]
This guy claims to have a solution: https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/

**Comment by urapadmin** [comment]
yippieh. It wasn't even the Flask upload after all! It was wfastcgi.py! One has to download the latest version from github: https://github.com/microsoft/PTVS/tree/master/Python/Product/WFastCgi instead of using the one pip install installs.

**Comment by urapadmin** [comment]
### @test 0.13.15
I reopen this because of the recent Python / Flask update. It needs to be tested again.

**Comment by lbestock** [comment]
@mcornacchia25 
Meghan, you've had a practice exercise for uploading images. So you get this one for 0.13.15 - please upload both a workstation and use a file import for a big ZIP.

Ah ha, let's do two in one. Before @mcornacchia25 hits it, @luizaogs why don't you test some file picking by making the default workstations have images instead of dummies again? So in order, Luiza will file pick us some big fat workstations. Report back here when done. Once that is done, Meghan do a new prepare and download and check to make sure that indeed there are no more dummy images. Add a few contexts or something to add some more images, and then upload to test this. (And then check the director's view to make sure your additions show up there.)

**Comment by luizaogs** [comment]
Done.

**Comment by mcornacchia25** [comment]
No dummy images. I added some images and they show up properly in the file repository as well as the Director's view. For the other upload you're talking about, do I just need to make a zip file containing a bunch of photos and then upload using the import files button?

**Comment by urapadmin** [comment]
> No dummy images. I added some images and they show up properly in the file repository as well as the Director's view. For the other upload you're talking about, do I just need to make a zip file containing a bunch of photos and then upload using the import files button?

you can put whatever you like into a zip file. The idea here is to make it big. Images are often the best way to get there. You may very well upload a 500MB ZIP if you can create one.

**Comment by mcornacchia25** [comment]
I uploaded a 1 GB test file and everything seemed to work ok as far as I could tell. It took a minute or two, but I assume that's to be expected.

**Comment by urapadmin** [comment]
actually a minute or two? That would be rather fast. And the file is there and you can download it again?

**Comment by mcornacchia25** [comment]
I'll be honest, I don't know how to download anything from the file repository, but it definitely looks like it's there and shows the file size as 1000 MB.

**Comment by luizaogs** [comment]
What is its description (or a tag), Meghan? I can try to download it.

**Comment by mcornacchia25** [comment]
It's the first file in Meghan Test. Its thumbnail is an octopus looking thing.

**Comment by luizaogs** [comment]
I can download it (it took a while), but it downloads as a .bin rather than a zip and then I get the error below since I guess I need a specific type of program to open such a file. Not sure if that's what you intend to happen, Lutz?

(Meghan, fyi, to download a file you just click on the downwards arrow on the top left of the image's thumbnail in the file edit window.)

<img width="374" alt="Screen Shot 2022-02-04 at 10 23 41 PM" src="https://user-images.githubusercontent.com/67970402/152628502-2e432e79-7570-4a48-b988-ac52b92218b9.png">

**Comment by urapadmin** [comment]
without having looked into it I would suppose that Meghan actually uploaded a .bin, no?

**Comment by urapadmin** [comment]
just for curiosity‘s sake: Roughly how long did it take you to upload the GB? An hour, half an hour, 15 minutes …?

And what about the download?

**Comment by mcornacchia25** [comment]
Yeah that's right. It was probably like 10 minutes at most to upload, though I think it was faster than that if I remember correctly.

**Comment by luizaogs** [comment]
Ahh she had said a zip above so I assumed some weird conversion had taken place.

The download took about 10 minutes.

**Comment by luizaogs** [comment]
I guess this can be closed, too?

**Comment by urapadmin** [comment]
upload and download speeds are all okay. So the new Python and Flask versions have improved things rather than caused new issues. I looked it up in the logs: The file was a .bin to begin with. So I close this.
