### ISSUE TITLE
QR Code Detection should be fed jpegs only, conversion necessary beforehand

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#842]
OpenCV cannot open NEFs and that's the image manipulation library we are using. I have to convert the raw files first to jpg.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/763#issuecomment-662695362_

**Comment by urapadmin** [comment]
### kiosk 0.8.16
- [ ] importing QR Coded NEFs should work now. 
- [ ] importing other file types with QR Codes should still work, too.

**Comment by lbestock** [comment]
@mcornacchia25 I'm adding you on this ticket because you are the one with a Canon! Both setting your camera to raw and taking QR code photos are new for you and I'm happy to zoom if you want to figure it out together (I'm not in today - Providence public schools closed for the ice storm that isn't happening).

**Comment by mcornacchia25** [comment]
Just tried this out with Canon raw files and everything worked as expected. I added some without QR codes which took a bit longer than usual (probably the larger file size) and then I did a couple with QR codes and they got assigned properly.

**Comment by urapadmin** [comment]
what import did you use? I'd like to look at one of the raw files.

**Comment by mcornacchia25** [comment]
import_2022-02-13 16:32:1 was the one with the QR codes

**Comment by urapadmin** [comment]
thanks. I close this then.
