### ISSUE TITLE
upgrade to Python 3.10.1

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/kiosk#903]
One of the reasons is that it has the zoneinfo module included. 
But it is time to keep up with versions, anyhow. 

Question is: How to upgrade a virtual environment?

**Comment by urapadmin** [comment]
### @test kiosk 0.13.14
- Upgraded to python 3.10.1 (can be checked in administration)
- needs a rather extensive test together with #911

**Comment by luizaogs** [comment]
Hmm I am unable to create a workstation currently. I cleared the cache in case that had anything to do with it, but it didn't help. Neither filemaker recording nor file export ones work -- after I click the check button nothing happens (but the button disappears and reappears, so it looks like something should have).

**Comment by lbestock** [comment]
I report this problem, too.

@luizaogs and @mcornacchia25 let's create new tickets when we run into bugs while testing this. Will help prevent baroque tickets and make sure @urapadmin can tackle them one by one.

**Comment by urapadmin** [comment]
ja, please report all bugs and whatnot in new tickets. It would become a nightmare here, otherwise. And please don't forget to add at least the "kiosk" label.

**Comment by luizaogs** [comment]
Does it make sense to report all bugs in other tickets but to have a sort of checklist going here, with what has been tested by whom, so that we do not double test things? Unless we're all supposed to test everything here, too.

**Comment by lbestock** [comment]
It makes very good sense to have a checklist going here. Some things are going to get tested by all of us more or less by accident because tasks overlap, and that's fine, but some tasks we should split up. Everyone feel free to add to this list - I'm sure it's not comprehensive. (Also I know both of you, Luiza and Meghan, are in the process of moving back to your respective campuses and will not have time for this immediately.)

- [ ] File import and File repository. @mcornacchia25 Please test all possible types of getting information attached to the images, and then check in the file repository that they can be found by searching context and/or description when they have such things. (This will mean playing with QR codes; too.)
- [ ] Backup and restore. @lbestock 
- [ ] File manager. @luizaogs 
- [ ] Quality control. @luizaogs 
- [ ] File picking. @luizaogs 
- [ ] Workstation download/upload. @mcornacchia25 
- [ ] Users and privileges. @lbestock 
- [ ] Director's view - everyone each time they actually perform a synchronization.

**Comment by luizaogs** [comment]
Tuesday would be fine.

**Comment by urapadmin** [comment]
@mcornacchia25, @lbestock: I have written a little thingy on file import in the wiki here: [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:user_manual:file_import#kiosk_file_repository_-_file_import](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:user_manual:file_import#kiosk_file_repository_-_file_import). Perhaps that helps understanding what is going on there.

**Comment by mcornacchia25** [comment]
I'm starting to work with the file import. I first tried to upload a bunch of jpegs using the default filter. It said that they were all uploaded successfully, but they do not show thumbnails in the file repository and I can seem to do anything else now, like search by something else. 

This is what it looks like:
<img width="1285" alt="Screen Shot 2022-02-04 at 3 01 45 PM" src="https://user-images.githubusercontent.com/96021337/152596073-527333dd-c72a-4c41-adb5-65cca043457b.png">

**Comment by mcornacchia25** [comment]
Another problem, this time with context from operating system file. As you can see above, I could use the default to assign things to Meghan Test, but this method it did not work. I know you talked in the wiki about some issues with spaces, so that's probably the issue, but I figured I'd mention it since it was a bit inconsistent from the user's end how it was working. I uploaded one with Office and that worked.

**Comment by urapadmin** [comment]
> I'm starting to work with the file import. I first tried to upload a bunch of jpegs using the default filter. It said that they were all uploaded successfully, but they do not show thumbnails in the file repository and I can seem to do anything else now, like search by something else.
> 
> This is what it looks like: <img alt="Screen Shot 2022-02-04 at 3 01 45 PM" width="1285" src="https://user-images.githubusercontent.com/96021337/152596073-527333dd-c72a-4c41-adb5-65cca043457b.png">
> 
> Refreshing seemed to fix it.

Battling the administration all day I am so happy to have a ticket. And this one is easy: It is a local cache issue of your Browser. What OS are you on? Apple? Is this SAFARI? Whatever it is: A full reload will help. That's ctrl+F5 on Windows and something else that I always forgot on Mac. (I can see your thumbnails!)

**Comment by urapadmin** [comment]
Oh. 

> Another problem, this time with context from operating system file. As you can see above, I could use the default to assign things to Meghan Test, but this method it did not work. I know you talked in the wiki about some issues with spaces, so that's probably the issue, but I figured I'd mention it since it was a bit inconsistent from the user's end how it was working. I uploaded one with Office and that worked.

Documenting things is hard for me. Takes a lot of time (non-native) and getting into a user's perspective isn't always easy. So feel free to improve the documentation on the basis of your experiences.
The PVD Test project interprets filenames the default way, which means it would take a space as separating the identifier from the description. So it would try to assign the image to a context "Meghan" and use "Test" as the description. 
How exactly did it refuse the import? With an error?

**Comment by mcornacchia25** [comment]
It just didn't assign it. It would probably make sense not to allow trenches to be made with spaces in them, though that may be a convention already that I was not aware of. I'll try to check that QR codes are working now.

**Comment by mcornacchia25** [comment]
This space also causes problems with the QR code, saying that the identifier "Meghan" is not recognized, but otherwise the QR code seems to be working. I also tried uploading an image to both a trench and individual context and extracting a description. Based on the wiki, I thought this was supposed to add a contextual description, but it instead added a context independent description in both cases. The wiki also mentions that you should be able to only check the description box to add a candid with a description, but when I tried to do that, I got this error:

<img width="775" alt="Screen Shot 2022-02-04 at 9 28 44 PM" src="https://user-images.githubusercontent.com/96021337/152625540-cb3c296e-908a-478b-862a-aa94288f0484.png">

**Comment by urapadmin** [comment]
> This space also causes problems with the QR code, saying that the identifier "Meghan" is not recognized, but otherwise the QR code seems to be working. I also tried uploading an image to both a trench and individual context and extracting a description. Based on the wiki, I thought this was supposed to add a contextual description, but it instead added a context independent description in both cases. The wiki also mentions that you should be able to only check the description box to add a candid with a description, but when I tried to do that, I got this error:

I have turned this into three separate tickets: #1337, #1338, #1339. In future you would make my life easier if you tried to separate issues into different tickets or at least different comments. It gets a bit hard otherwise to see where we are.

**Comment by urapadmin** [comment]
@arch-kiosk/test: As far as I can see none of the reported issues are bound to the original topic. Besides some nuances the file import and the Qr Code recognition works and all the other checkboxes are checked. So from my point of view we could close this here.

**Comment by luizaogs** [comment]
I shall close it, then.
